apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-11-28T12:19:30Z"
  labels:
    app: front
  name: front-deployment
  namespace: default
  resourceVersion: "7803"
  uid: 30b3af2d-f1ef-4022-9efc-bcccdc5705ab
spec:
  clusterIP: 10.102.185.240
  clusterIPs:
  - 10.102.185.240
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32035
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}